INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (1,13000000,true,"Corgi","Corgi là giống chó dễ thương, năng động, với cặp mông to siêu đáng yêu. Tuy nhiên một vấn đề được rất nhiều người yêu chó quan tâm chính là : giá bán chó corgi có mắc không?","Bình thường, đã tiêm chủng",1,1,"https://www.vietpet.vn/wp-content/uploads/2019/09/794426-333x500.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (2,60000000,true,"Akita Inu","Nếu đã từng xem bộ phim Nhật Bản nổi tiếng “Hachiko”, chắc hẳn bạn sẽ nhận ra giống chó này. Chó Akita rất ngoan, trung thành, thông minh và quấn quýt với gia chủ. Có lẽ chính bởi vậy mà nó được rất nhiều gia đình ưa chuộng.","Bình thường,khỏe, nhanh nhẹn",3,1,"https://anh.24h.com.vn/upload/4-2016/images/2016-12-10/1481376981-148109980433581-1.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (3,130000000,true,"Toucan","Mặc dù có rất nhiều loại chim, vẹt sặc sỡ với giá phải chăng nhưng những người giàu, đặc biệt là những người sành lại thường tìm kiếm cho mình một thú cưng hiếm và kì lạ như chú chim Toucan này. Chim Toucan chỉ được tìm thấy phổ biến ở khu vực miền nam Mexico, phía Trung và Nam Mỹ","Bình thường, đã tiêm chủng",5,5,"https://anh.24h.com.vn/upload/4-2016/images/2016-12-10/1481376982-148109982284608-2.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (4,16000000,true,"Savannah","Savannah là giống mèo quý có vẻ ngoài không khác gì một chú báo đốm. Thân hình mảnh, dẻo dai, đặc biệt là “thần thái sang chảnh”, đầy “uy lực” của giống mèo này có thể chinh phục được bất cứ ví tiền nào. Những chú mèo Savannah còn nổi tiếng thông minh và trung thành y như một chú chó.","Bình thường, đã tiêm chủng",3,2,"https://anh.24h.com.vn/upload/4-2016/images/2016-12-10/1481376982-148109983711774-3.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (5,23000000,true,"Striped","Nuôi trăn làm thú cưng thực sự là một sở thích dũng cảm.","Bình thường, đã tiêm chủng",4,8,"https://anh.24h.com.vn/upload/4-2016/images/2016-12-10/1481376983-148109987066521-5.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (6,32000000,true,"Vẹt Palm Cockatoo","Palm Cockatoo có nguồn gốc từ New Guinea và Úc, đây chính là một trong số những loài vẹt có mào đẹp nhất thế giới. Chiếc mào tuyệt mỹ đầy phong cách cùng bộ lông màu đen hoặc tro xám đặc trưng khiến chúng khó bị lẫn với bất cứ loại thú cưng nào.","Bình thường, đã tiêm chủng",1,5,"https://anh.24h.com.vn/upload/4-2016/images/2016-12-10/1481376983-1481099901197-7.jpg");

INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (7,2319000000000,true,"Sư tử trắng","Mặc dù nuôi sư tử không còn quá lạ nhưng một chú sư tử trắng thì lại là chuyện khác. Sư tử trắng là loại biến dị di truyền cự kì hiếm, chỉ tìm thấy ở một số khu bảo tồn động vật hoang dã tại Nam Phi.","Bình thường, hiền ,ngoan ngoãn",12,8,"https://anh.24h.com.vn/upload/4-2016/images/2016-12-10/1481376983-148109996517596-10.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (8,12063983541,true,"Chó Ngao Tây Tạng","Ngao Tây Tạng là một trong những giống chó có “dòng dõi quý tộc” và có thân hình lớn nhất thế giới. Nguồn gốc của giống chó này tới từ Nepal và Trung Quốc. Một chú Ngao Tây Tạng trưởng thành có thể nặng tới 160kg và cao 84cm","Bình thường, hiền lành",1,1,"https://anh.24h.com.vn/upload/4-2016/images/2016-12-10/1481376984-148110000238882-12.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (9,324799556,true,"Vẹt Macaw Hyacinth","Macaw có nguồn gốc từ miền đông và trung Nam Mỹ, đây là loài vẹt lớn nhất trên hành tinh. Nó có một mỏ khỏe mổ hạt cứng. Cùng với việc trở thành một trong những loài chim lớn nhất thế giớ","Bình thường,đẹp. thuần chủng",17,8,"https://image.viettimes.vn/w800/Uploaded/2019/aohuooh/2018_10_08/hyacinthmacawmostexpensiveanimals_wbdl.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (10,220000000,true,"Khỉ De Brazza","Loài khỉ De Brazza hay còn được gọi là khỉ đầm lầy sinh trưởng ở các khu vực ngập nước thuộc Trung Phi. Tên của chúng được đặt theo nhà thám hiểm người Pháp Pierre Savorgnan de Brazza, chúng rất khó phát hiện hành tung nhờ khả năng lẩn trốn thiên tài.","Bình thường, đã tiêm chủng",4,13,"https://image.viettimes.vn/w666/Uploaded/2019/aohuooh/2018_10_08/2_choq.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (11,230000,true,"Nhím Kiểng Muối Tiêu","Những chú nhím muối tiêu với màu lông đen trắng muối tiêu cổ điển. Tuy hay cuộn mình nhút nhát nhưng nhím kiểng muối tiêu rất hiền lành và dễ thương. Chỉ cần được vuốt ve và cho ăn, bạn đã thu phục em nó rồi đó. Nhím kiểng không cắn hay bắn lông như nhím hoang dã đâu nhé","Bình thường, đã tiêm chủng",4,14,"https://www.petxinh.net/wp-content/uploads/2014/08/hedgehog-468228_960_720-300x199.jpg");
INSERT INTO dong_vat(id, gia_tien, gioi_tinh, tendv, thong_tin_co_ban, tinh_trang_suc_khoe, chu_nhan_id, loai_dong_vat_id,url) VALUES (12,23000000,true,"Rồng Nam Mỹ – Green Iguana ","Rồng Nam Mỹ là loài bò sát có kích cỡ lớn, hầm hố. Rồng Nam Mỹ có xuất xứ từ vùng Caribe Nam Mỹ. Trên lưng thường có sừng (gai) nhìn hầm hố như một chú rồng trong chuyện cổ tích. Nhưng chúng lại rất hiền lành, Rồng nam mỹ ăn gì bạn biết không nào? những chú Kỳ Nhông Nam Mỹ này chỉ ăn hoa quả, và rau cỏ thôi. Chúng rất từ tốn lành tính. ","Bình thường, hiền lành",20,15,"https://www.petxinh.net/wp-content/uploads/2016/06/iguana-621x320.jpg");